const assert = require("node:assert/strict");
const test = require("node:test");
const { submitReturnShipment, reportReturnReceived, confirmReturnReceived, correctReturnShipment, validateShipmentFields } = require("../backend/services/orderClaimService");
const { getPayoutEligibility } = require("../backend/services/deliveryConfirmationService");

const buyer = { uid: "buyer", email: "buyer@example.com" }; const seller = { uid: "seller", email: "seller@example.com" }; const admin = { uid: "admin", email: "admin@example.com" };
const baseOrder = { ilanId: "listing-1", aliciUid: buyer.uid, saticiUid: seller.uid, odemeDurumu: true, durum: "Teslim Edildi", teslimatDogrulandi: true, hakEdisBlokeli: true, hakEdisDurumu: "İncelemede", aktifTalepId: "claim-1", hakEdisBlokeBaslangic: new Date("2026-09-01T00:00:00Z"), hakEdisBlokeBitis: new Date("2026-09-03T00:00:00Z") };
const baseClaim = { orderId: "order-1", buyerUid: buyer.uid, sellerUid: seller.uid, tip: "iade", durum: "kabul_edildi", payoutBlock: true, returnFlowStatus: "bekliyor" };
function fakeFirestore({ order = baseOrder, claim = baseClaim, listing = { urunTipi: "fiziksel", fizikselKargo: true } } = {}) {
  const data = new Map([["siparisler/order-1", { ...order }], ["orderClaims/claim-1", { ...claim }]]); if (listing) data.set("ilanlar/listing-1", { ...listing });
  const ref = (path) => ({ path, id: path.split("/").at(-1) }); const snap = (value) => ({ exists: value !== undefined, data: () => value });
  return { data, collection(name) { return { doc(id) { return ref(`${name}/${id}`); } }; }, async runTransaction(work) { const tx = { async get(target) { return snap(data.get(target.path)); }, update(target, value) { data.set(target.path, { ...data.get(target.path), ...value }); }, create(target, value) { data.set(target.path, { ...value }); }, delete(target) { data.delete(target.path); } }; return work(tx); } };
}
const shipment = { carrier: "Yurtiçi Kargo", trackingNumber: "ABC-12345" };
test("1 buyer kabul edilmiş fiziksel iade için shipment girebilir", async () => { const db = fakeFirestore(); const result = await submitReturnShipment({ firestore: db, claimId: "claim-1", user: buyer, body: shipment }); assert.equal(result.carrier, shipment.carrier); });
test("2 başka buyer shipment giremez", async () => await assert.rejects(submitReturnShipment({ firestore: fakeFirestore(), claimId: "claim-1", user: { uid: "other" }, body: shipment }), /giremezsiniz/));
test("3 seller buyer shipment endpointini kullanamaz", async () => await assert.rejects(submitReturnShipment({ firestore: fakeFirestore(), claimId: "claim-1", user: seller, body: shipment }), /giremezsiniz/));
test("4 itiraz claim için shipment açılamaz", async () => await assert.rejects(submitReturnShipment({ firestore: fakeFirestore({ claim: { ...baseClaim, tip: "itiraz" } }), claimId: "claim-1", user: buyer, body: shipment }), /İtiraz/));
for (const status of ["acik", "inceleniyor", "reddedildi"]) test(`5 ${status} claim için shipment açılamaz`, async () => await assert.rejects(submitReturnShipment({ firestore: fakeFirestore({ claim: { ...baseClaim, durum: status } }), claimId: "claim-1", user: buyer, body: shipment }), /kabul edilmiş/));
test("6 dijital ürün için shipment açılamaz", async () => await assert.rejects(submitReturnShipment({ firestore: fakeFirestore({ listing: { urunTipi: "dijital", fizikselKargo: false } }), claimId: "claim-1", user: buyer, body: shipment }), /Dijital/));
test("7 carrier zorunludur", () => assert.throws(() => validateShipmentFields({ trackingNumber: "ABC" }), /zorunludur/));
test("8 tracking zorunludur", () => assert.throws(() => validateShipmentFields({ carrier: "Aras" }), /zorunludur/));
test("9 carrier uzunluğu reddedilir", () => assert.throws(() => validateShipmentFields({ carrier: "x".repeat(81), trackingNumber: "ABC" }), /80/));
test("9b tracking uzunluğu reddedilir", () => assert.throws(() => validateShipmentFields({ carrier: "Aras", trackingNumber: "x".repeat(101) }), /100/));
test("10 server returnShippedAt yazar", async () => { const db = fakeFirestore(); const now = new Date("2026-09-03T10:00:00Z"); await submitReturnShipment({ firestore: db, claimId: "claim-1", user: buyer, body: shipment, now: () => now }); assert.equal(db.data.get("orderClaims/claim-1").returnShippedAt, now); });
test("11 buyer timestamp girdisi kullanılmaz", async () => { const db = fakeFirestore(); const trusted = new Date("2026-09-03T10:00:00Z"); await submitReturnShipment({ firestore: db, claimId: "claim-1", user: buyer, body: { ...shipment, returnShippedAt: new Date(0) }, now: () => trusted }); assert.equal(db.data.get("orderClaims/claim-1").returnShippedAt, trusted); });
test("12 aynı shipment duplicate idempotent", async () => { const db = fakeFirestore(); await submitReturnShipment({ firestore: db, claimId: "claim-1", user: buyer, body: shipment }); const second = await submitReturnShipment({ firestore: db, claimId: "claim-1", user: buyer, body: shipment }); assert.equal(second.idempotent, true); });
test("13 buyer farklı tracking ile overwrite yapamaz", async () => { const db = fakeFirestore(); await submitReturnShipment({ firestore: db, claimId: "claim-1", user: buyer, body: shipment }); await assert.rejects(submitReturnShipment({ firestore: db, claimId: "claim-1", user: buyer, body: { ...shipment, trackingNumber: "NEW-1" } }), /değiştirilemez/); });
async function shippedDb() { const db = fakeFirestore(); await submitReturnShipment({ firestore: db, claimId: "claim-1", user: buyer, body: shipment }); return db; }
test("14 seller kendi iadesinde received report yapabilir", async () => assert.equal((await reportReturnReceived({ firestore: await shippedDb(), claimId: "claim-1", user: seller })).idempotent, false));
test("15 başka seller report yapamaz", async () => await assert.rejects(reportReturnReceived({ firestore: await shippedDb(), claimId: "claim-1", user: { uid: "other" } }), /yapamazsınız/));
test("16 seller report trusted delivery sayılmaz", async () => { const db = await shippedDb(); await reportReturnReceived({ firestore: db, claimId: "claim-1", user: seller }); assert.equal(db.data.get("orderClaims/claim-1").returnFlowStatus, "kargoya_verildi"); });
test("17 seller report payoutBlock kaldırmaz", async () => { const db = await shippedDb(); await reportReturnReceived({ firestore: db, claimId: "claim-1", user: seller }); assert.equal(db.data.get("orderClaims/claim-1").payoutBlock, true); });
test("18 admin return received doğrulayabilir", async () => assert.equal((await confirmReturnReceived({ firestore: await shippedDb(), claimId: "claim-1", admin })).idempotent, false));
test("20 admin confirm server timestamp yazar", async () => { const db = await shippedDb(); const now = new Date("2026-09-04T00:00:00Z"); await confirmReturnReceived({ firestore: db, claimId: "claim-1", admin, now: () => now }); assert.equal(db.data.get("orderClaims/claim-1").returnReceivedAt, now); });
test("21 admin confirmation type yazar", async () => { const db = await shippedDb(); await confirmReturnReceived({ firestore: db, claimId: "claim-1", admin }); assert.equal(db.data.get("orderClaims/claim-1").returnReceivedConfirmationType, "admin"); });
test("22 admin confirm payoutBlock true bırakır", async () => { const db = await shippedDb(); await confirmReturnReceived({ firestore: db, claimId: "claim-1", admin }); assert.equal(db.data.get("orderClaims/claim-1").payoutBlock, true); });
test("23 admin confirm order hakEdisBlokeli true bırakır", async () => { const db = await shippedDb(); await confirmReturnReceived({ firestore: db, claimId: "claim-1", admin }); assert.equal(db.data.get("siparisler/order-1").hakEdisBlokeli, true); });
test("24 admin confirm wallet değiştirmez", async () => { const db = await shippedDb(); await confirmReturnReceived({ firestore: db, claimId: "claim-1", admin }); assert.equal([...db.data.keys()].some((key) => key.startsWith("wallets/")), false); });
test("25 admin confirm 48 saat timestamp değiştirmez", async () => { const db = await shippedDb(); await confirmReturnReceived({ firestore: db, claimId: "claim-1", admin }); assert.deepEqual(db.data.get("siparisler/order-1").hakEdisBlokeBitis, baseOrder.hakEdisBlokeBitis); });
test("26 verified return ve accepted claim payout eligible değildir", async () => { const db = await shippedDb(); await confirmReturnReceived({ firestore: db, claimId: "claim-1", admin }); assert.equal(getPayoutEligibility(db.data.get("siparisler/order-1"), new Date("2026-09-05T00:00:00Z")).eligible, false); });
test("27 return received refundCompleted yazmaz", async () => { const db = await shippedDb(); await confirmReturnReceived({ firestore: db, claimId: "claim-1", admin }); assert.equal("refundCompleted" in db.data.get("orderClaims/claim-1"), false); });
test("28 return received finansal kapanış yazmaz", async () => { const db = await shippedDb(); await confirmReturnReceived({ firestore: db, claimId: "claim-1", admin }); assert.equal("paymentStatus" in db.data.get("orderClaims/claim-1"), false); });
test("29 admin tracking düzeltmesi audit yazar", async () => { const db = await shippedDb(); await correctReturnShipment({ firestore: db, claimId: "claim-1", admin, body: { carrier: "Aras", trackingNumber: "NEW-2" } }); const claim = db.data.get("orderClaims/claim-1"); assert.equal(claim.returnTrackingNumber, "NEW-2"); assert.equal(claim.returnShipmentCorrectedBy, admin.uid); });
test("30 duplicate admin confirm idempotent", async () => { const db = await shippedDb(); await confirmReturnReceived({ firestore: db, claimId: "claim-1", admin }); assert.equal((await confirmReturnReceived({ firestore: db, claimId: "claim-1", admin })).idempotent, true); });
