import { useCallback, useEffect, useState } from "react";
import { adminApi } from "../../config/adminApi";
import "../../styles/components/admin-order-claims.css";

const ACTIONS = { acik: [["inceleniyor", "İncelemeye Al"], ["reddedildi", "Reddet"]], inceleniyor: [["kabul_edildi", "Kabul Et"], ["reddedildi", "Reddet"]] };
function dateText(value) { const date = value?._seconds ? new Date(value._seconds * 1000) : value?.seconds ? new Date(value.seconds * 1000) : null; return date ? date.toLocaleString("tr-TR") : "-"; }
export default function AdminOrderClaims() {
  const [claims, setClaims] = useState([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(null); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setLoading(true); const data = await adminApi("/order-claims"); setClaims(data.claims || []); } catch (err) { setError(err.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  async function change(claim, status) { try { setBusy(claim.id); setError(""); await adminApi(`/order-claims/${encodeURIComponent(claim.id)}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); await load(); } catch (err) { setError(err.message); } finally { setBusy(null); } }
  async function confirmReturn(claim) { const note = window.prompt("Geri teslim doğrulama notu (isteğe bağlı):", "") ?? null; if (note === null) return; try { setBusy(claim.id); await adminApi(`/order-claims/${encodeURIComponent(claim.id)}/confirm-return-received`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ note }) }); await load(); } catch (err) { setError(err.message); } finally { setBusy(null); } }
  async function correctShipment(claim) { const carrier = window.prompt("Kargo firması:", claim.returnCarrier || ""); if (carrier === null) return; const trackingNumber = window.prompt("Takip numarası:", claim.returnTrackingNumber || ""); if (trackingNumber === null) return; try { setBusy(claim.id); await adminApi(`/order-claims/${encodeURIComponent(claim.id)}/return-shipment`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ carrier, trackingNumber }) }); await load(); } catch (err) { setError(err.message); } finally { setBusy(null); } }
  async function startRefund(claim) { if (!window.confirm("Doğrulanmış ürün bedeli için Iyzico iadesini başlatmak istiyor musunuz? Bu işlem wallet muhasebesini kapatmaz.")) return; try { setBusy(claim.id); setError(""); await adminApi(`/order-claims/${encodeURIComponent(claim.id)}/refund`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ description: "Admin onaylı fiziksel ürün iadesi" }) }); await load(); } catch (err) { setError(err.message); await load(); } finally { setBusy(null); } }
  function refundLabel(status) { if (status === "success") return "Iyzico İadesi Başarılı"; if (status === "failed") return "Iyzico İadesi Başarısız"; if (status === "unknown") return "İade Sonucu Doğrulanmalı"; return "Henüz başlatılmadı"; }
  return <section className="admin-section admin-claims"><h2>İade / İtiraz Talepleri</h2>{error && <p className="admin-claims-error">{error}</p>}{loading ? <p>Yükleniyor...</p> : claims.length === 0 ? <p>Henüz talep bulunmuyor.</p> : <div className="admin-claims-grid">{claims.map((claim) => <article key={claim.id} className="admin-claim-card"><div className="admin-claim-heading"><strong>{claim.tip === "iade" ? "İade Talebi" : "Sipariş İtirazı"}</strong><span>{claim.durum}</span></div><dl><div><dt>Sipariş</dt><dd>{claim.orderId}</dd></div><div><dt>Neden</dt><dd>{claim.nedenKodu || "-"}</dd></div><div><dt>Açıklama</dt><dd>{claim.aciklama || "-"}</dd></div><div><dt>Alıcı</dt><dd>{claim.buyerEmail || claim.buyerUid || "-"}</dd></div><div><dt>Satıcı</dt><dd>{claim.sellerEmail || claim.sellerUid || "-"}</dd></div><div><dt>Tarih</dt><dd>{dateText(claim.createdAt)}</dd></div>{claim.tip === "iade" && claim.durum === "kabul_edildi" && <><div><dt>Geri dönüş</dt><dd>{claim.returnFlowStatus || "bekliyor"}</dd></div><div><dt>Kargo</dt><dd>{claim.returnCarrier || "-"}</dd></div><div><dt>Takip no</dt><dd>{claim.returnTrackingNumber || "-"}</dd></div><div><dt>Kargoya verildi</dt><dd>{dateText(claim.returnShippedAt)}</dd></div><div><dt>Satıcı beyanı</dt><dd>{claim.sellerReturnReceivedReported ? "Satıcı teslim aldığını bildirdi" : "Bekleniyor"}</dd></div>{claim.returnFlowStatus === "teslim_dogrulandi" && <><div><dt>Refund tutarı</dt><dd>{claim.refundPreview?.amount != null ? `${Number(claim.refundPreview.amount).toFixed(2)} ${claim.refundPreview.currency}` : "Doğrulanamadı"}</dd></div><div><dt>İşlem</dt><dd>{claim.refundPreview?.paymentTransactionIdMasked || "Eksik"}</dd></div><div><dt>Provider</dt><dd>{refundLabel(claim.refundProviderStatus)}</dd></div></>}</>}</dl>{ACTIONS[claim.durum]?.length > 0 && <div className="admin-claim-actions">{ACTIONS[claim.durum].map(([status, label]) => <button type="button" key={status} disabled={busy === claim.id} onClick={() => change(claim, status)}>{busy === claim.id ? "İşleniyor..." : label}</button>)}</div>}{claim.tip === "iade" && claim.durum === "kabul_edildi" && ["kargoya_verildi", "teslim_dogrulandi"].includes(claim.returnFlowStatus) && <div className="admin-claim-actions"><button type="button" disabled={busy === claim.id} onClick={() => correctShipment(claim)}>Kargo Bilgisini Düzelt</button>{claim.returnFlowStatus === "kargoya_verildi" && <button type="button" disabled={busy === claim.id} onClick={() => confirmReturn(claim)}>Geri Teslimi Doğrula</button>}{claim.returnFlowStatus === "teslim_dogrulandi" && !claim.refundProviderStatus && <button type="button" disabled={busy === claim.id || !claim.refundPreview?.available} onClick={() => startRefund(claim)}>Iyzico İadesini Başlat</button>}</div>}</article>)}</div>}</section>;
}
