import { useCallback, useEffect, useMemo, useState } from "react";
import { adminApi } from "../../config/adminApi";
import "../../styles/components/admin-operations.css";

function money(value) { return `${Number(value || 0).toLocaleString("tr-TR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ₺`; }
function dateText(value) { const seconds = value?._seconds ?? value?.seconds; const date = seconds != null ? new Date(seconds * 1000) : value ? new Date(value) : null; return date && !Number.isNaN(date.getTime()) ? date.toLocaleString("tr-TR") : "-"; }
const HEALTH_LABELS = { payment: "Ödemeler", orderFlow: "Sipariş Akışı", earnings48h: "48 Saat Hakediş", marketplaceSettlement: "Marketplace Settlement", scheduledMaintenance: "Zamanlanmış Bakım", backendErrors: "Backend" };
const HEALTH_TEXT = { HEALTHY: "✅ Normal", WARNING: "🟠 Kontrol", CRITICAL: "🔴 Sorun" };

export function AdminOperationsOverview() {
  const [dashboard, setDashboard] = useState(null); const [error, setError] = useState("");
  useEffect(() => { adminApi("/overview").then(setDashboard).catch((err) => setError(err.message)); }, []);
  if (error) return <section className="admin-section admin-dashboard-unavailable"><h2>Dashboard bilgileri şu anda alınamıyor</h2><p>Birkaç dakika sonra tekrar deneyin.</p><details><summary>Teknik detay</summary><code>{error}</code></details></section>;
  if (!dashboard) return <section className="admin-section admin-operation-loading" role="status">Operasyon verileri yükleniyor...</section>;
  const overall = dashboard.overall || { status: "ATTENTION", actionRequiredCount: 0 };
  const health = dashboard.health || {}; const today = dashboard.today || {}; const metrics = dashboard.metrics || {};
  return <section className="admin-section admin-control-center" id="admin-dashboard"><div className={`admin-overall ${overall.status === "HEALTHY" ? "healthy" : "attention"}`}><span aria-hidden="true">{overall.status === "HEALTHY" ? "✓" : "!"}</span><div><h2>{overall.status === "HEALTHY" ? "Her şey yolunda" : `⚠️ ${Number(overall.actionRequiredCount || 0)} işlem müdahale bekliyor`}</h2><p>{overall.status === "HEALTHY" ? "Şu anda müdahale gerektiren işlem bulunmuyor." : "Yalnız açık istisnalar İşlem Gerektirenler bölümünde gösteriliyor."}</p></div></div><div className="admin-dashboard-grid"><article><h3>Sistem Sağlığı</h3><div className="admin-health-list">{Object.entries(HEALTH_LABELS).map(([key, label]) => <div key={key}><span>{label}</span><strong className={(health[key] || "WARNING").toLowerCase()}>{HEALTH_TEXT[health[key]] || "🟠 Kontrol"}</strong></div>)}</div><small>Son bakım: {dateText(health.lastMaintenanceAt)}</small></article><article><h3>Bugünün Özeti</h3><dl><div><dt>Bugünkü sipariş</dt><dd>{Number(today.orders || 0).toLocaleString("tr-TR")}</dd></div><div><dt>Bugünkü satış</dt><dd>{money(today.salesAmount)}</dd></div><div><dt>Teslim edilen</dt><dd>{Number(today.deliveredOrders || 0)}</dd></div><div><dt>Açık itiraz</dt><dd>{Number(metrics.openClaims || 0)}</dd></div><div><dt>Müdahale bekleyen</dt><dd>{Number(overall.actionRequiredCount || 0)}</dd></div></dl></article></div></section>;
}

export function AdminUsers() {
  const [users, setUsers] = useState([]); const [nextPageToken, setNextPageToken] = useState(null); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async (token = "") => { try { setLoading(true); setError(""); const data = await adminApi(`/users${token ? `?pageToken=${encodeURIComponent(token)}` : ""}`); setUsers((old) => token ? [...old, ...(data.users || [])] : (data.users || [])); setNextPageToken(data.nextPageToken || null); } catch (err) { setError(err.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const visible = useMemo(() => { const term = search.trim().toLocaleLowerCase("tr-TR"); return users.filter((user) => !term || [user.displayName, user.email, user.uid].join(" ").toLocaleLowerCase("tr-TR").includes(term)); }, [search, users]);
  async function toggle(user) { const next = !user.disabled; if (!window.confirm(`${user.email || user.uid} hesabını ${next ? "pasifleştirmek" : "yeniden açmak"} istiyor musunuz?`)) return; try { setBusy(user.uid); setError(""); await adminApi(`/users/${encodeURIComponent(user.uid)}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ disabled: next }) }); setUsers((old) => old.map((item) => item.uid === user.uid ? { ...item, disabled: next } : item)); } catch (err) { setError(err.message); } finally { setBusy(""); } }
  return <section className="admin-section" id="admin-users"><div className="admin-section-heading"><div><h2>Kullanıcı Yönetimi</h2><p>Firebase Auth kullanıcıları; hassas ödeme ve kimlik bilgileri gösterilmez.</p></div><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Ad, e-posta veya UID ara" /></div>{error && <p className="admin-operation-error">{error}</p>}{loading && users.length === 0 ? <p>Yükleniyor...</p> : visible.length === 0 ? <p>Kullanıcı bulunamadı.</p> : <div className="admin-table-wrap"><table><thead><tr><th>Kullanıcı</th><th>E-posta doğrulama</th><th>Sağlayıcı</th><th>Son giriş</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{visible.map((user) => <tr key={user.uid}><td><strong>{user.displayName || "İsimsiz kullanıcı"}</strong><br /><small>{user.email || user.uid}</small></td><td>{user.emailVerified ? "✅ Doğrulandı" : "⌛ Doğrulanmadı"}</td><td>{user.providers.join(", ") || "-"}</td><td>{dateText(user.lastSignInAt)}</td><td>{user.disabled ? "⛔ Pasif" : "✅ Aktif"}</td><td><button type="button" disabled={busy === user.uid} onClick={() => toggle(user)}>{busy === user.uid ? "İşleniyor..." : user.disabled ? "Yeniden Aç" : "Kısıtla"}</button></td></tr>)}</tbody></table></div>}{nextPageToken && <button className="admin-load-more" type="button" disabled={loading} onClick={() => load(nextPageToken)}>{loading ? "Yükleniyor..." : "Sonraki 50 kullanıcıyı yükle"}</button>}</section>;
}

export function AdminAuditLog() {
  const [logs, setLogs] = useState([]); const [error, setError] = useState("");
  useEffect(() => { adminApi("/audit-logs").then((data) => setLogs(data.logs || [])).catch((err) => setError(err.message)); }, []);
  return <section className="admin-section" id="admin-audit"><h2>Admin İşlem Geçmişi</h2><p>Kritik ilan, mağaza ve kullanıcı işlemlerinin son 50 kaydı.</p>{error && <p className="admin-operation-error">{error}</p>}{!error && logs.length === 0 ? <p>Henüz audit kaydı bulunmuyor.</p> : <div className="admin-audit-list">{logs.map((log) => <article key={log.id}><strong>{log.action}</strong><span>{log.targetType}: {log.targetId}</span><small>{log.adminEmail || log.adminUid || "Admin"} · {dateText(log.createdAt)}</small></article>)}</div>}</section>;
}
