import { useEffect, useMemo, useState } from "react";
import { doc, getDoc } from "firebase/firestore";
import { db } from "../firebase";
import { cancelOrderClaim, createOrderClaim, submitReturnShipment } from "../services/orderClaimApi";
import "../styles/components/order-claim-form.css";

const REASONS = { iade: ["Ürün beklentimi karşılamadı", "Yanlış ürün geldi", "Hasarlı ürün", "Eksik ürün", "Diğer"], itiraz: ["Ürün ulaşmadı", "Yanlış ürün", "Hasarlı ürün", "Eksik ürün", "Siparişle ilgili başka sorun", "Diğer"] };
const DIGITAL_REASONS = ["Dosya indirilemiyor", "Yanlış dosya teslim edildi", "Dosya bozuk/açılamıyor", "İlan açıklamasıyla uyuşmuyor", "Diğer"];
function dateValue(value) { if (!value) return null; if (typeof value.toDate === "function") return value.toDate(); const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; }
export default function OrderClaimForm({ order, onSubmitted, onCancelled }) {
  const [claimWindowCheck] = useState(() => Date.now());
  const [open, setOpen] = useState(false); const [type, setType] = useState("itiraz"); const [reasonCode, setReasonCode] = useState(""); const [description, setDescription] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [claim, setClaim] = useState(null); const [carrier, setCarrier] = useState(""); const [trackingNumber, setTrackingNumber] = useState("");
  const status = order.durum === "Kargoya Verildi" ? "Kargoda" : order.durum === "Teslim" ? "Teslim Edildi" : order.durum;
  const digital = order.urunTipi === "dijital" || order.fizikselKargo === false || order.dijitalTeslimat === true || order.teslimatTipi === "dijital";
  const allowedTypes = useMemo(() => { const values = []; const deadline = dateValue(order.hakEdisBlokeBitis); if (digital) { if (status === "Teslim Edildi" && order.teslimatDogrulandi === true && order.odemeDurumu === true && deadline && deadline.getTime() >= claimWindowCheck) values.push("itiraz"); return values; } if (status === "Teslim Edildi" && order.teslimatDogrulandi === true) values.push("iade"); if (["Kargoda", "Teslim Edildi"].includes(status) && order.odemeDurumu === true) values.push("itiraz"); return values; }, [claimWindowCheck, digital, order, status]);
  useEffect(() => { let active = true; if (!order.aktifTalepId) { setClaim(null); return undefined; } getDoc(doc(db, "orderClaims", order.aktifTalepId)).then((snap) => { if (active && snap.exists()) setClaim({ id: snap.id, ...snap.data() }); }).catch(() => {}); return () => { active = false; }; }, [order.aktifTalepId]);
  async function cancel() { if (!order.aktifTalepId || !window.confirm("Açık talebinizi iptal etmek istiyor musunuz?")) return; setSaving(true); setMessage(""); try { await cancelOrderClaim(order.aktifTalepId); setMessage("Talebiniz iptal edildi."); onCancelled?.(); } catch (error) { setMessage(error.message); } finally { setSaving(false); } }
  async function sendShipment(event) { event.preventDefault(); setSaving(true); setMessage(""); try { const result = await submitReturnShipment(claim.id, { carrier, trackingNumber }); setClaim((old) => ({ ...old, returnFlowStatus: "kargoya_verildi", returnCarrier: result.carrier, returnTrackingNumber: result.trackingNumber })); setMessage("İade kargoya verildi. Satıcıya geri teslim doğrulaması bekleniyor."); } catch (error) { setMessage(error.message); } finally { setSaving(false); } }
  if (order.hakEdisBlokeli === true) return <div className="order-return-flow"><p className="order-claim-message">Talebiniz incelemede.</p>{claim?.tip === "iade" && claim.durum === "kabul_edildi" && (!claim.returnFlowStatus || claim.returnFlowStatus === "bekliyor") && <form className="order-return-form" onSubmit={sendShipment}><strong>İade Kargo Bilgilerini Gir</strong><label>Kargo Firması<input value={carrier} maxLength="80" required onChange={(event) => setCarrier(event.target.value)} /></label><label>Takip Numarası<input value={trackingNumber} maxLength="100" required onChange={(event) => setTrackingNumber(event.target.value)} /></label><button type="submit" disabled={saving}>{saving ? "Kaydediliyor..." : "İade Kargosunu Bildir"}</button></form>}{claim?.returnFlowStatus === "kargoya_verildi" && <div className="order-return-summary"><strong>İade kargoya verildi</strong><span>Kargo firması: {claim.returnCarrier}</span><span>Takip no: {claim.returnTrackingNumber}</span><span>Satıcıya geri teslim doğrulaması bekleniyor.</span></div>}{claim?.returnFlowStatus === "teslim_dogrulandi" && <div className="order-return-summary"><strong>Geri teslim yönetici tarafından doğrulandı</strong><span>{claim.refundProviderStatus === "success" ? "Ödeme kuruluşu üzerinden para iadesi başlatıldı." : "Finansal iade işlemi henüz tamamlanmadı."}</span></div>}{claim?.durum === "acik" && order.aktifTalepId && <button type="button" className="order-claim-trigger" disabled={saving} onClick={cancel}>{saving ? "İptal ediliyor..." : "Açık Talebi İptal Et"}</button>}{message && <p className="order-claim-message" role="status">{message}</p>}</div>;
  if (!allowedTypes.length) return null;
  async function submit(event) { event.preventDefault(); setSaving(true); setMessage(""); try { const result = await createOrderClaim(order.id, { type, reasonCode, description }); setMessage(result.message); setOpen(false); onSubmitted?.(result); } catch (error) { setMessage(error.message); } finally { setSaving(false); } }
  function show() { const initial = allowedTypes[0]; setType(initial); setReasonCode((digital ? DIGITAL_REASONS : REASONS[initial])[0]); setOpen(true); }
  const reasons = digital ? DIGITAL_REASONS : REASONS[type];
  return <><button type="button" className="order-claim-trigger" onClick={show}>{digital ? "Dijital ürünle ilgili sorun bildir" : "İade / İtiraz Bildir"}</button>{message && <p className="order-claim-message" role="status">{message}</p>}{open && <div className="order-claim-backdrop" role="presentation"><form className="order-claim-modal" onSubmit={submit}><h3>{digital ? "Dijital ürün sorunu bildir" : "İade / İtiraz Bildir"}</h3><p>Talebiniz admin incelemesine alınır; otomatik ücret iadesi yapılmaz.</p>{!digital && <label>Talep tipi<select value={type} onChange={(e) => { setType(e.target.value); setReasonCode(REASONS[e.target.value][0]); }}>{allowedTypes.map((value) => <option key={value} value={value}>{value === "iade" ? "İade Talebi" : "Sipariş İtirazı"}</option>)}</select></label>}<label>Neden<select value={reasonCode} onChange={(e) => setReasonCode(e.target.value)}>{reasons.map((reason) => <option key={reason}>{reason}</option>)}</select></label><label>Açıklama<textarea maxLength="2000" rows="4" value={description} onChange={(e) => setDescription(e.target.value)} /></label><div className="order-claim-actions"><button type="button" onClick={() => setOpen(false)} disabled={saving}>Vazgeç</button><button type="submit" disabled={saving}>{saving ? "Gönderiliyor..." : "İncelemeye Gönder"}</button></div></form></div>}</>;
}
