import { useMemo, useState } from "react";
import { cancelOrderClaim, createOrderClaim } from "../services/orderClaimApi";
import "../styles/components/order-claim-form.css";

const REASONS = { iade: ["Ürün beklentimi karşılamadı", "Yanlış ürün geldi", "Hasarlı ürün", "Eksik ürün", "Diğer"], itiraz: ["Ürün ulaşmadı", "Yanlış ürün", "Hasarlı ürün", "Eksik ürün", "Siparişle ilgili başka sorun", "Diğer"] };
export default function OrderClaimForm({ order, onSubmitted, onCancelled }) {
  const [open, setOpen] = useState(false); const [type, setType] = useState("itiraz"); const [reasonCode, setReasonCode] = useState(""); const [description, setDescription] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const status = order.durum === "Kargoya Verildi" ? "Kargoda" : order.durum === "Teslim" ? "Teslim Edildi" : order.durum;
  const allowedTypes = useMemo(() => { const values = []; if (status === "Teslim Edildi" && order.teslimatDogrulandi === true && order.urunTipi !== "dijital") values.push("iade"); if (["Kargoda", "Teslim Edildi"].includes(status) && order.odemeDurumu === true) values.push("itiraz"); return values; }, [order, status]);
  async function cancel() { if (!order.aktifTalepId || !window.confirm("Açık talebinizi iptal etmek istiyor musunuz?")) return; setSaving(true); setMessage(""); try { await cancelOrderClaim(order.aktifTalepId); setMessage("Talebiniz iptal edildi."); onCancelled?.(); } catch (error) { setMessage(error.message); } finally { setSaving(false); } }
  if (order.hakEdisBlokeli === true) return <div><p className="order-claim-message">Talebiniz incelemede.</p>{order.aktifTalepId && <button type="button" className="order-claim-trigger" disabled={saving} onClick={cancel}>{saving ? "İptal ediliyor..." : "Açık Talebi İptal Et"}</button>}{message && <p className="order-claim-message" role="status">{message}</p>}</div>;
  if (!allowedTypes.length) return null;
  async function submit(event) { event.preventDefault(); setSaving(true); setMessage(""); try { const result = await createOrderClaim(order.id, { type, reasonCode, description }); setMessage(result.message); setOpen(false); onSubmitted?.(result); } catch (error) { setMessage(error.message); } finally { setSaving(false); } }
  function show() { const initial = allowedTypes[0]; setType(initial); setReasonCode(REASONS[initial][0]); setOpen(true); }
  return <><button type="button" className="order-claim-trigger" onClick={show}>İade / İtiraz Bildir</button>{message && <p className="order-claim-message" role="status">{message}</p>}{open && <div className="order-claim-backdrop" role="presentation"><form className="order-claim-modal" onSubmit={submit}><h3>İade / İtiraz Bildir</h3><p>Talebiniz incelenir; bu form otomatik ücret iadesi anlamına gelmez.</p><label>Talep tipi<select value={type} onChange={(e) => { setType(e.target.value); setReasonCode(REASONS[e.target.value][0]); }}>{allowedTypes.map((value) => <option key={value} value={value}>{value === "iade" ? "İade Talebi" : "Sipariş İtirazı"}</option>)}</select></label><label>Neden<select value={reasonCode} onChange={(e) => setReasonCode(e.target.value)}>{REASONS[type].map((reason) => <option key={reason}>{reason}</option>)}</select></label><label>Açıklama<textarea maxLength="2000" rows="4" value={description} onChange={(e) => setDescription(e.target.value)} /></label><div className="order-claim-actions"><button type="button" onClick={() => setOpen(false)} disabled={saving}>Vazgeç</button><button type="submit" disabled={saving}>{saving ? "Gönderiliyor..." : "Talebi Gönder"}</button></div></form></div>}</>;
}
